openapi: 3.0.1
info:
  title: IntgHelloWorldAPI
  description: API Definition of IntgHelloWorldAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/intghelloworld
paths:
  /fulfillOrder:
    get:
      responses:
        default:
          description: Default response
